apiVersion: v1
kind: ResourceQuota
metadata:
  name: system-quota
  namespace: mini-cloud-system
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "5"
    persistentvolumeclaims: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-quota
  namespace: mini-cloud-platform
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: applications-quota
  namespace: mini-cloud-applications
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-quota
  namespace: mini-cloud-data
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "8"
    persistentvolumeclaims: "8"